global:
  scrape_interval: 5s      # How often to scrape targets
  evaluation_interval: 15s  # How often to evaluate rules

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Points to your Django app on host machine
    metrics_path: '/metrics'
